# Generated by Django 4.2.1 on 2023-06-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_users_alter_subscriptionlog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='myuser',
        ),
        migrations.AddField(
            model_name='users',
            name='emailid',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='phoneno',
            field=models.CharField(default='NULL', max_length=10),
        ),
    ]
