# Generated by Django 4.2.1 on 2023-06-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0003_remove_users_myuser_users_emailid_users_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='emailid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='phoneno',
            field=models.CharField(max_length=10),
        ),
    ]
